name: education_app
description: "A new Flutter project."


publish_to: 'none' 



version: 1.0.0+1

environment:
  sdk: ^3.5.4




dependencies:
  flutter:
    sdk: flutter


  bloc: ^8.1.4
  cupertino_icons: ^1.0.8
  chewie: ^1.8.5
  dartz: ^0.10.1
  flutter_bloc: ^8.1.6
  equatable: ^2.0.7
  file_picker: ^8.1.6
  font_awesome_flutter: ^10.8.0
  get_it: ^8.0.3
  iconly: ^1.0.1
  image_picker: ^1.1.2
  intl: ^0.20.1
  lottie: ^3.2.0
  open_file: ^3.5.10
  path_provider: ^2.1.5
  provider: ^6.1.2
  shared_preferences: ^2.3.4
  smooth_page_indicator: ^1.2.0+3
  swipe_to: ^1.0.6
  url_launcher: ^6.3.1
  http: ^1.2.2
  youtube_metadata: ^1.0.1
  mocktail: ^1.0.4
  video_thumbnail: ^0.5.3
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.1
  cloud_firestore: ^5.6.2
  firebase_storage: ^12.4.1
  firebase_ui_auth: ^1.16.1
  uuid: ^4.5.1
  flutter_card_swiper: ^7.0.2
  supabase_flutter: ^2.8.4
  badges: ^3.1.2
  file_icon: ^1.0.0


dependency_overrides:
  http: any
  video_thumbnail: any
  intl: any

dev_dependencies:
  bloc_test: ^9.1.7
  flutter_test:
    sdk: flutter


  
  very_good_analysis: ^7.0.0
  flutter_lints: ^4.0.0
  firebase_auth_mocks: ^0.14.1
  google_sign_in_mocks: ^0.3.0
  fake_cloud_firestore: ^3.1.0
  firebase_storage_mocks: ^0.7.0





flutter:

  
  
  
  uses-material-design: true

  assets:
    - assets/vectors/
    - assets/images/
    - assets/lottie/
    - assets/icons/

  fonts:
    - family: Aeonik
      fonts:
        - asset: assets/fonts/aeonik/AeonikTRIAL-Bold.otf
          weight: 700
        - asset: assets/fonts/aeonik/AeonikTRIAL-BoldItalic.otf
          style: italic
          weight: 700
        - asset: assets/fonts/aeonik/AeonikTRIAL-Light.otf
          weight: 300
        - asset: assets/fonts/aeonik/AeonikTRIAL-LightItalic.otf
          style: italic
          weight: 300
        - asset: assets/fonts/aeonik/AeonikTRIAL-Regular.otf
          weight: 400
        - asset: assets/fonts/aeonik/AeonikTRIAL-RegularItalic.otf
          style: italic
          weight: 400

    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/poppins/Poppins-ExtraBold.ttf
          weight: 800
  
  
  

  
  

  
  

  
  
  

  
