// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```//// testt
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD37X79sQZJByQnWbsphZ9GY7PXhFfTHco',
    appId: '1:702672804524:web:dfc70fd2d966650e8c5d09',
    messagingSenderId: '702672804524',
    projectId: 'education-app-460e5',
    authDomain: 'education-app-460e5.firebaseapp.com',
    storageBucket: 'education-app-460e5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfYT-bLsjL53eKz2uIk0Xo2dYdK6nmLEg',
    appId: '1:702672804524:android:201639b5e450f28e8c5d09',
    messagingSenderId: '702672804524',
    projectId: 'education-app-460e5',
    storageBucket: 'education-app-460e5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDL3uiLD4aqfcxEl6Pvs1sRiuRtbTHzasY',
    appId: '1:702672804524:ios:2e89b2cebb90f2368c5d09',
    messagingSenderId: '702672804524',
    projectId: 'education-app-460e5',
    storageBucket: 'education-app-460e5.firebasestorage.app',
    iosBundleId: 'com.eduapp.educationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDL3uiLD4aqfcxEl6Pvs1sRiuRtbTHzasY',
    appId: '1:702672804524:ios:2e89b2cebb90f2368c5d09',
    messagingSenderId: '702672804524',
    projectId: 'education-app-460e5',
    storageBucket: 'education-app-460e5.firebasestorage.app',
    iosBundleId: 'com.eduapp.educationApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD37X79sQZJByQnWbsphZ9GY7PXhFfTHco',
    appId: '1:702672804524:web:8e3e6eda37ba55a88c5d09',
    messagingSenderId: '702672804524',
    projectId: 'education-app-460e5',
    authDomain: 'education-app-460e5.firebaseapp.com',
    storageBucket: 'education-app-460e5.firebasestorage.app',
  );
}
